In [18]:
#16. Crea un array numpy di dimensione 3x3 con valori casuali.

import numpy as np

array_casuale = np.random.rand(3, 3)

print("Array numpy di dimensione 3x3 con valori casuali:")
print(array_casuale)


Array numpy di dimensione 3x3 con valori casuali:
[[0.13458344 0.38930667 0.93838752]
 [0.80547187 0.2477013  0.61100637]
 [0.34212886 0.84355159 0.97908324]]


In [9]:
#17. Scrivi un programma che calcoli la somma di tutti gli elementi in un array numpy.

array_numpy = np.array([[5, 23, 45],
                        [85, 72, 8],
                        [17, 48, 39]])

somma_totale = np.sum(array_numpy)

print("Somma di tutti gli elementi nell'array numpy:", somma_totale)


Somma di tutti gli elementi nell'array numpy: 342


In [11]:
#18. Crea un array numpy e calcolane la media, mediana e varianza.

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

media = np.mean(arr1)
mediana = np.median(arr1)
varianza = np.var(arr1)

print("Array:", arr1)
print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)


Array: [1 2 3 4 5 6 7 8 9]
Media: 5.0
Mediana: 5.0
Varianza: 6.666666666666667


In [27]:
#19. Scrivi un programma che moltiplichi due matrici numpy.

matrice1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrice2 = np.array([[7, 8 , 9],
                     [10, 11, 12]])
                   


prodotto = matrice1 * matrice2

print("Matrice 1:")
print(matrice1)
print("\nMatrice 2:")
print(matrice2)
print("\nProdotto delle due matrici:")
print(prodotto)


Matrice 1:
[[1 2 3]
 [4 5 6]]

Matrice 2:
[[ 7  8  9]
 [10 11 12]]

Prodotto delle due matrici:
[[ 7 16 27]
 [40 55 72]]


In [23]:
# 19. Altra opzione 
matrice1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrice2 = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])


prodotto = np.dot(matrice1, matrice2)

print("Matrice 1:")
print(matrice1)
print("\nMatrice 2:")
print(matrice2)
print("\nProdotto delle due matrici:")
print(prodotto)


Matrice 1:
[[1 2 3]
 [4 5 6]]

Matrice 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Prodotto delle due matrici:
[[ 58  64]
 [139 154]]


In [29]:
#20. Crea un array numpy e ordinalo in modo ascendente.


array_numpy = np.array([23, 15, 74, 21, 55, 79, 22, 96, 35])

array_ordinato = np.sort(array_numpy)

print("Array numpy originale:", array_numpy)
print("Array numpy ordinato in modo ascendente:", array_ordinato)


Array numpy originale: [23 15 74 21 55 79 22 96 35]
Array numpy ordinato in modo ascendente: [15 21 22 23 35 55 74 79 96]
